# config/app.yml for rails-settings-cached
defaults: &defaults
  Site_Header: "ShameBird"
  Site_Sub_Header: "Hello world!"
  # User_Name: "lulu"
  # Password: "secret"
  Email: "example@example.com"
  Posts_Paginate: "6"
  Microblogs_Paginate: "10"
  Albums_Paginate: "12"
  Comments_Paginate: "20"
  Theme_Color: "#dd2333"
  Banner_Image: "s.jpg"
  Banner_Background_Color: "#dd2333"


development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
